fix `Test freezes with "Maximum call stack size exceeded" error - Testcafe version 1.8.3 and up` (close #2405)
DevExpress/testcafe-hammerhead pull request #2411
Opened 2020-08-25 10:11 UTC by LavrovArtem

2020-08-25 14:48 UTC, LavrovArtem commented
@testcafe-build-bot retest

2020-08-26 05:59 UTC, LavrovArtem commented
@testcafe-build-bot retest

2020-08-26 06:05 UTC, Farfurix approved these changes

2020-08-26 08:25 UTC, miherlosev requested changes

2020-08-26 08:25 UTC, miherlosev commented on src/client/sandbox/upload/index.ts
> +        if (value === '' && UploadSandbox._getCurrentInfoManager(input).clearUploadInfo(input) && isIE && browserVersion > 10)
`if (value === '' && UploadSandbox._getCurrentInfoManager(input).clearUploadInfo(input) && isIE11)`

2020-08-26 08:25 UTC, miherlosev commented on test/client/fixtures/sandbox/node/attributes-test.js
>  if (!browserUtils.isIE || browserUtils.version !== 11) {
`if (!browserUtils.isIE11) {`

2020-08-26 08:25 UTC, miherlosev commented on test/client/fixtures/sandbox/node/attributes-test.js
> +if (browserUtils.isChrome) {
Add note why we run this test only for Chrome.

2020-08-26 09:54 UTC, miherlosev approved these changes

2020-08-26 11:45 UTC, LavrovArtem commented
@testcafe-build-bot retest

2020-08-26 12:52 UTC, merged