Fix `Testcafe hammerhead processing transforms break JavaScript without semicolons as line endings` (close #2392)
DevExpress/testcafe-hammerhead pull request #2416
Opened 2020-08-26 13:29 UTC by Farfurix

2020-08-31 16:39 UTC, Farfurix commented
@testcafe-build-bot retest

2020-09-01 06:43 UTC, LavrovArtem requested changes

2020-09-01 06:43 UTC, LavrovArtem commented on src/processing/script/transform.ts
> +        changes.push(getChange(state.newExpressionAncestor, parentType));
```diff
- changes.push(getChange(state.newExpressionAncestor, parentType));
+ changes.push(getChange(state.newExpressionAncestor, state.newExpressionAncestorParent.type));
```

2020-09-01 09:57 UTC, Farfurix commented
@testcafe-build-bot retest

2020-09-01 10:14 UTC, LavrovArtem approved these changes

2020-09-01 10:29 UTC, Farfurix commented
@testcafe-build-bot retest

2020-09-01 11:37 UTC, Farfurix commented
@testcafe-build-bot retest

2020-09-01 12:48 UTC, merged