[WIP] Update body mutation tracking when adding the body to the document
DevExpress/testcafe-hammerhead pull request #2421
Opened 2020-08-28 15:22 UTC by Ogurecher

## Please don't review until we get the credentials for Devexpress/testcafe#5322 and test it on the user's scenario

## Purpose
_Describe the problem you want to address or the feature you want to implement._

## Approach
_Describe how your changes address the issue or implement the desired functionality in as much detail as possible._

## References
Closes Devexpress/testcafe#5322

## Pre-Merge TODO
- [x] Write tests for your proposed changes
- [ ] Make sure that existing tests do not fail

2020-09-04 05:40 UTC, Farfurix approved these changes

2020-09-07 14:34 UTC, LavrovArtem requested changes
Minor issues

2020-09-07 14:34 UTC, LavrovArtem commented on test/client/data/live-node-list/getBodyByTagName.html
> +            window.top.bodyExistsBeforeAttachingBody = bodyExists();
I think that it is unnecessary to save the test data in the top window. Just save it in the current iframe and use `iframe.contentWindow.<prop>` in your test.

2020-09-07 14:34 UTC, LavrovArtem commented on test/client/fixtures/sandbox/node/html-collection-wrapper-test.js
> +        test('getElementsByTagName(\'body\') updates correctly GH-5322', function () {
Use \` or `"` instead of `\'`.

2020-09-07 14:34 UTC, LavrovArtem commented on test/client/fixtures/sandbox/node/html-collection-wrapper-test.js
> +                    assertions.push([!window.top.bodyExistsBeforeAttachingBody, true, 'getElementsByTagName(\'body\') returned an empty collection before the body was created']);
Just use `strictEqual`.

2020-09-08 08:36 UTC, LavrovArtem approved these changes

2020-09-08 09:24 UTC, AndreyBelym approved these changes

2020-09-08 09:26 UTC, merged