Fix the issues that appeared after merging #2448
DevExpress/testcafe-hammerhead pull request #2460
Opened 2020-10-19 10:31 UTC by wentwrong

## Purpose
Fix the issues introduced in the #2448

## Approach
* Revert changes in the `destination-location.ts` file (because functions from this file are used in many places in the code). 
* Separate handling of the location object properties of the "about:blank" document in `LocationWrapper`
* Instead of calling the location "origin" getter, call the active document's origin when processing "ancestorOrigins". According to the [specification](https://www.w3.org/TR/2017/WD-html52-20170228/browsers.html#ancestor-origins-array):
> 5. Append the Unicode serialization of current’s active document’s origin to output as a new value.
## References
#2448 

## Pre-Merge TODO
- [ ] Write tests for your proposed changes
- [ ] Make sure that existing tests do not fail

2020-10-20 07:20 UTC, wentwrong commented
@testcafe-build-bot retest

2020-10-20 09:22 UTC, wentwrong commented
@testcafe-build-bot retest

2020-10-20 12:32 UTC, LavrovArtem requested changes

2020-10-20 12:32 UTC, LavrovArtem commented on src/client/sandbox/code-instrumentation/location/wrapper.ts
> +
```js
const frameElement       = domUtils.getFrameElement(window);
const inIframeWithoutSrc = frameElement && domUtils.isIframeWithoutSrc(frameElement);
const parsedDestLocation = inIframeWithoutSrc ? window.location : getParsedDestLocation();

return parsedDestLocation[property];
```

2020-10-21 08:09 UTC, LavrovArtem approved these changes

2020-10-21 08:20 UTC, merged