Should not emit error after a destination response is ended (304 status case, related to #2315) (close DevExpress/testcafe#5025)
DevExpress/testcafe-hammerhead pull request #2474
Opened 2020-11-06 08:24 UTC by LavrovArtem

2020-11-06 11:07 UTC, miherlosev requested changes

2020-11-06 11:07 UTC, miherlosev commented on src/request-pipeline/utils.ts
> +            if (!ctx.isNotModified) {
Let's put this code to the `ctx.calculateIsDestResReadableEnded ()`.

2020-11-09 05:07 UTC, miherlosev requested changes

2020-11-09 05:07 UTC, miherlosev commented on src/request-pipeline/utils.ts
> +            if (!ctx.contentInfo.isNotModified && !ctx.contentInfo.isRedirect) {
https://github.com/DevExpress/testcafe-hammerhead/pull/2474#discussion_r518681846

2020-11-09 08:33 UTC, miherlosev approved these changes

2020-11-09 09:15 UTC, LavrovArtem commented
@testcafe-build-bot retest

2020-11-09 09:31 UTC, Farfurix approved these changes

2020-11-09 09:39 UTC, merged