Update typescript version up to 3.7.5 (close #2472)
DevExpress/testcafe-hammerhead pull request #2476
Opened 2020-11-10 10:36 UTC by LavrovArtem

2020-11-10 11:26 UTC, miherlosev requested changes

2020-11-10 11:26 UTC, miherlosev commented on src/client/sandbox/code-instrumentation/location/ancestor-origins-wrapper.ts
> +class Temp {}
```js
class DOMStringListInheritor {}
```

2020-11-10 11:26 UTC, miherlosev commented on src/client/sandbox/node/live-node-list/html-collection-wrapper.ts
> +class Temp {}
`class HTMLCollectionInheritor {}`

2020-11-10 11:26 UTC, miherlosev commented on src/client/sandbox/node/live-node-list/html-collection-wrapper.ts
> +        /* temp */
Add a more clear comment

2020-11-12 05:44 UTC, Farfurix approved these changes

2020-11-12 05:45 UTC, miherlosev approved these changes

2020-11-12 05:45 UTC, merged