Support web workers created by a Blob URL (close #1221)
DevExpress/testcafe-hammerhead pull request #2482
Opened 2020-11-17 08:04 UTC by LavrovArtem

2020-11-17 11:15 UTC, miherlosev requested changes

2020-11-17 11:15 UTC, miherlosev commented on src/client/sandbox/fetch.ts
> +            if (sandbox._waitHammerheadSettings)
```js
if (sandbox.getSettingInProgress())
     return sandbox.delayUntilGetSettings(() => this.fetch.apply(this, args));
```

and so on

2020-11-18 10:54 UTC, miherlosev requested changes

2020-11-18 10:54 UTC, miherlosev commented on src/client/worker/base-with-delayed-settings.ts
> +import Promise from 'pinkie';
Rename file to `src/client/worker/sandbox-base-with-delayed-settings.ts`

2020-11-18 13:17 UTC, miherlosev approved these changes

2020-11-19 05:34 UTC, Farfurix approved these changes

2020-11-19 07:16 UTC, merged