fix `Adobe Launch Analytics requests are not fired when accessing a page with TestCafe` (close #2453)
DevExpress/testcafe-hammerhead pull request #2484
Opened 2020-11-18 10:08 UTC by LavrovArtem

2020-11-18 11:15 UTC, miherlosev requested changes

2020-11-18 11:15 UTC, miherlosev commented on src/client/sandbox/node/document/index.ts
> +                if (referrer !== nativeReferrer && isSpecialPage(referrer))
For which cases the `referrer !== nativeReferrer` condition is necessary?

2020-11-20 08:03 UTC, miherlosev approved these changes

2020-11-23 11:59 UTC, merged

2020-11-24 06:02 UTC, mariuspahontu commented
thank you, for your work!