Added the noImplicitThis rule to tsconfig
DevExpress/testcafe-hammerhead pull request #2495
Opened 2020-12-01 09:52 UTC by Ogurecher

## Purpose
Synchronize typescript options with testcafe for monorepo migration.

## Approach
Added the noImplicitThis rule to tsconfig, fixed errors.

## References
Part of https://github.com/DevExpress/testcafe/issues/5666

## Pre-Merge TODO
- [ ] Make sure that existing tests do not fail

2020-12-10 09:59 UTC, AndreyBelym approved these changes

2020-12-11 10:57 UTC, LavrovArtem requested changes

2020-12-11 10:57 UTC, LavrovArtem commented on src/client/sandbox/event/listeners.ts
> +        return function (this: unknown, e: Event) {
`this: EventTarget`

2020-12-11 10:57 UTC, LavrovArtem commented on src/client/sandbox/event/listeners.ts
> +        return function (this: unknown, e: Event) {
`this: EventTarget`

2020-12-11 10:57 UTC, LavrovArtem commented on src/client/sandbox/node/window.ts
> +            overrideFunction(window.Object, 'assign', function (this: Object, target: object, ...sources: any[]) {
`this: ObjectConstructor`

2020-12-11 10:57 UTC, LavrovArtem commented on src/client/sandbox/node/window.ts
> +        return function (this: unknown) {
`this: DOMTokenList`

2020-12-11 10:57 UTC, LavrovArtem commented on src/client/sandbox/xhr.ts
> +        overrideFunction(xmlHttpRequestProto, 'send', function (this: XMLHttpRequest, ...args: [(string | Document | Blob | ArrayBufferView | ArrayBuffer | FormData | URLSearchParams | ReadableStream
We don't process the arguments of the send function, and because we can just write `...args: [any]`

2020-12-11 10:57 UTC, LavrovArtem commented on src/client/transport-worker/request.ts
> +function handleEvent (this: unknown, e: ProgressEvent) {
![image](https://user-images.githubusercontent.com/5373460/101894639-8a489a80-3bb7-11eb-9bbd-27ad5dfc1f1a.png)

2020-12-11 17:53 UTC, LavrovArtem approved these changes

2020-12-11 17:53 UTC, merged