Fix wrong document.write executing in iframe with srcdoc (close #2494)
DevExpress/testcafe-hammerhead pull request #2498
Opened 2020-12-02 10:14 UTC by LavrovArtem

2020-12-02 12:37 UTC, miherlosev requested changes

2020-12-02 12:37 UTC, miherlosev commented on src/utils/init-script-for-iframe-template.ts
> +import INTERNAL_PROPS from '../processing/dom/internal-properties';
I guess it's time to create folder structure for the self-removing scripts
```js
src/utils/self-removing-script/
    create.js
    init-script-for-iframe-template.ts
    ...
    put here all self-removing scripts from client and server sides
                                               
```

2020-12-03 12:31 UTC, miherlosev approved these changes

2020-12-03 12:40 UTC, LavrovArtem commented
@testcafe-build-bot retest

2020-12-03 13:18 UTC, merged