fix: don't override deprecated electron func
DevExpress/testcafe-hammerhead pull request #2500
Opened 2020-12-04 08:35 UTC by wentwrong

vm.runInDebugContext [deprecated](https://nodejs.org/api/deprecations.html#deprecations_dep0069_vm_runindebugcontext_string) in V8 and in Node.js 10+.
We should not override it without additional check. 

How to test manually:

1. `gulp test-client --dev`
2. "electron.js":
```js
// Modules to control application life and create native browser window
const {app, BrowserWindow} = require('electron')

function createWindow () {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
        nodeIntegration: true
    }
  })

  mainWindow.loadURL('http://localhost:2000')

  // Open the DevTools.
  mainWindow.webContents.openDevTools()
}

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.whenReady().then(() => {
  createWindow()
  
  app.on('activate', function () {
    // On macOS it's common to re-create a window in the app when the
    // dock icon is clicked and there are no other windows open.
    if (BrowserWindow.getAllWindows().length === 0) createWindow()
  })
})

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', function () {
  if (process.platform !== 'darwin') app.quit()
})

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and require them here.
```
3. `electron app.js`
4. Run client tests

2020-12-04 09:03 UTC, wentwrong commented
@testcafe-build-bot retest

2020-12-04 10:40 UTC, wentwrong commented
@testcafe-build-bot retest

2020-12-04 12:16 UTC, miherlosev requested changes

2020-12-04 12:16 UTC, miherlosev commented on test/client/fixtures/sandbox/electron-test.js
> +if (browserUtils.isElectron) {
Rewrite in the following way:
```js
test('test', function () {
   const windowMock      = createElectronWindowMock();
   const electronSandbox = new ElectronSandbox();

   electronSandbox.attach(windowMock);
   
   const vmMock =  windowMock.require('vm');

   ok(vmMock.runInDebugContext('code'));

   windowMock.removeRunInDebugContextFromVM();

   electronSandbox.attach(windowMock);
   
   const vmMock =  windowMock.require('vm');

   notOk(vmMock.runInDebugContext('code'));




   
});
```

2020-12-07 05:49 UTC, miherlosev approved these changes

2020-12-07 05:50 UTC, merged