fix `Wrong handler is called for unautorized cross-domain request` (close #1263)
DevExpress/testcafe-hammerhead pull request #2501
Opened 2020-12-07 09:44 UTC by LavrovArtem

2020-12-07 09:52 UTC, miherlosev approved these changes

2020-12-07 13:06 UTC, Farfurix approved these changes

2020-12-15 08:26 UTC, LavrovArtem commented on src/session/events/info.ts
> +        this.statusCode = ctx.isSameOriginPolicyFailed ? 0 : ctx.destRes.statusCode;
!!! Maybe, we always need to return `ctx.destRes.statusCode`.

2020-12-15 08:26 UTC, LavrovArtem commented on src/typings/client.d.ts
> +declare const TextRange: {
delete it

2020-12-17 11:57 UTC, miherlosev requested changes

2020-12-17 13:51 UTC, LavrovArtem commented
[testcafe-hammerhead-17.2.0.zip](https://github.com/DevExpress/testcafe-hammerhead/files/5709867/testcafe-hammerhead-17.2.0.zip)

2020-12-17 13:58 UTC, miherlosev approved these changes

2020-12-17 15:40 UTC, Farfurix approved these changes

2020-12-17 15:45 UTC, LavrovArtem commented
don't merge it

2020-12-22 08:48 UTC, LavrovArtem commented on src/utils/headers.ts
> +const AUTHORIZATION_PREFIX = '~~~this prefix added by testcafe for the authorization controlling~~~ ';
check it please

2020-12-22 09:31 UTC, titerman requested changes

2020-12-22 09:31 UTC, titerman commented on src/utils/headers.ts
> +const AUTHORIZATION_PREFIX = '~~~this prefix added by testcafe for the authorization controlling~~~ ';
```suggestion
const AUTHENTICATE_PREFIX  = '~~~TestCafe added this prefix to hide the authentication dialog box~~~ ';
const AUTHORIZATION_PREFIX = '~~~TestCafe added this prefix to control the authorization flow~~~ ';
```

2020-12-23 07:03 UTC, LavrovArtem commented
@testcafe-build-bot retest

2020-12-23 07:15 UTC, LavrovArtem commented
@testcafe-build-bot retest

2020-12-23 08:27 UTC, merged