fix regression of `Support web workers created by a Blob URL #2482`
DevExpress/testcafe-hammerhead pull request #2502
Opened 2020-12-07 12:59 UTC by LavrovArtem

2020-12-07 16:01 UTC, miherlosev requested changes

2020-12-08 10:18 UTC, miherlosev approved these changes

2020-12-08 10:27 UTC, miherlosev commented
@testcafe-build-bot retest

2020-12-08 11:42 UTC, LavrovArtem commented
@testcafe-build-bot retest

2020-12-08 12:32 UTC, merged