The global context info calculated once per context
DevExpress/testcafe-hammerhead pull request #2533
Opened 2020-12-30 13:24 UTC by LavrovArtem

2021-01-08 09:09 UTC, miherlosev requested changes

2021-01-08 09:09 UTC, miherlosev commented on src/client/sandbox/native-methods.ts
> +import globalContextInfo from '../utils/global-context-info';
I guess it's better to change the `getGlobalContextInfo` function in the following way

```js
const globalContenxtInfo = getGlobalContextInfoInternal () // calculate once

export default function getGlobalContextInfo () {
    return globalContenxtInfo;
}
```

2021-01-11 08:15 UTC, miherlosev approved these changes

2021-01-11 08:52 UTC, Farfurix approved these changes

2021-01-11 10:22 UTC, merged