Storage sandbox refactoring
DevExpress/testcafe-hammerhead pull request #2574
Opened 2021-01-29 09:18 UTC by LavrovArtem

2021-02-02 06:55 UTC, Farfurix approved these changes

2021-02-02 11:17 UTC, miherlosev requested changes
Excellent work. Just a few naming issues.

2021-02-02 11:17 UTC, miherlosev commented on src/client/sandbox/storages/index.ts
> +    StorageWrapper.HH_INTERNAL_METHODS);
`HH` is an unnecessary context.
Rename to `StorageWrapper.INTERNAL_METHODS`.

2021-02-02 11:17 UTC, miherlosev commented on src/client/sandbox/storages/index.ts
> +            storage.internal.lastState = storage.getCurrentState();
Restructure as the follows:
```js
storage.raiseStorageChanged(null, null, null);
storage.updateCurrentState();
```

2021-02-02 11:17 UTC, miherlosev commented on src/client/sandbox/storages/wrapper.ts
> +const INTERNAL_WEAK_MAP   = new WeakMap<StorageWrapper, StorageInternalInfo>();
Bad name.
Compare with `internal_number`, `internal_boolean`.
What about the `storageWrappersInternalInfo` name?

2021-02-02 12:15 UTC, LavrovArtem commented
[testcafe-hammerhead-19.3.0.zip](https://github.com/DevExpress/testcafe-hammerhead/files/5910996/testcafe-hammerhead-19.3.0.zip)

2021-02-02 12:58 UTC, miherlosev approved these changes

2021-02-02 13:01 UTC, LavrovArtem commented
https://github.com/DevExpress/testcafe/pull/5909

2021-02-16 12:13 UTC, LavrovArtem commented
@testcafe-build-bot retest

2021-02-16 12:42 UTC, merged