Http2 client
DevExpress/testcafe-hammerhead pull request #2598
Opened 2021-03-17 09:47 UTC by LavrovArtem

2021-03-24 07:37 UTC, miherlosev requested changes

2021-03-24 07:37 UTC, miherlosev commented on src/request-pipeline/context.ts
> +    destRes: http.IncomingMessage | FileStream | IncomingMessageLike | IncomingMessageLike | Http2Response = null;
It can be declared as a separate type - `DestinationResponse`

2021-03-24 07:37 UTC, miherlosev commented on src/request-pipeline/destination-request/http2.ts
> +    delete headers[HTTP2_HEADER_CONNECTION];
Remove in loop using the `Array.rightReduce` function.

2021-04-05 13:43 UTC, LavrovArtem commented
@testcafe-build-bot retest

2021-04-06 15:15 UTC, Farfurix commented
run monitor

2021-04-07 06:24 UTC, Farfurix requested changes

2021-04-07 06:24 UTC, Farfurix commented on src/request-pipeline/context.ts
> +type DestinationResponse = http.IncomingMessage | FileStream | IncomingMessageLike | IncomingMessageLike | Http2Response;
There is an accidental duplication of `IncomingMessageLike`.

2021-04-07 06:24 UTC, Farfurix commented on src/request-pipeline/context.ts
> +    private async _getDestResBody (res: IncomingMessageLike | http.IncomingMessage | FileStream | Http2Response): Promise<Buffer> {
We can use `DestinationResponse` here.

2021-04-07 06:24 UTC, Farfurix commented on src/request-pipeline/context.ts
> +    createCacheEntry (res: http.IncomingMessage | IncomingMessageLike | FileStream | Http2Response): void {
We can use `DestinationResponse` here.

2021-04-07 06:24 UTC, Farfurix commented on src/request-pipeline/utils.ts
> +        req.on('response', (res: http.IncomingMessage | FileStream | IncomingMessageLike | Http2Response) => {
We can use `DestinationResponse` here.

2021-04-07 09:38 UTC, miherlosev requested changes

2021-04-07 09:38 UTC, miherlosev commented on src/request-pipeline/cache.ts
> +export function create (reqOptions: RequestOptions, res: IncomingMessage | IncomingMessageLike | FileStream | Http2Response): RequestCacheEntry | undefined {
`export function create (reqOptions: RequestOptions, res: DestinationResponse): RequestCacheEntry | undefined {`

2021-04-07 09:38 UTC, miherlosev commented on src/request-pipeline/destination-request/http2.ts
> +import http2, { ClientHttp2Session, Http2Stream, IncomingHttpHeaders, IncomingHttpStatusHeader } from 'http2';
This file is large. I propose to split its content to few files
```js
http2/sessions.ts
http2/format-request-headers.ts
http2/create-response-like.ts
```

Also I propose to rename `makePseudoResponse` function to `createResponseLike`.

2021-04-07 09:38 UTC, miherlosev commented on src/request-pipeline/destination-request/index.ts
> +        const http2Session = this.opts.isHttps && !this.opts.isWebSocket &&
I propose to pack these instructions to the separate function:
```js

async __getLiveHttp2Session () {
   if (!this.opts.isHttps || this.opts.isWebSocket)
     return null;

    const origin  = ,this.opts.protocol + '//' + this.opts.host;
    const session = this.opts.isHttps && !this.opts.isWebSocket && await getHttp2Session(this.opts.requestId, origin);

   if (session.destroyed)
     return null;

 return session;

  
}
const http2Session = this._getLiveHttp2Session ();

if (http2Session)
    this._sendRealThroughHttp2(http2Session);
else
    this._sendReal(waitForData);
```

2021-04-09 05:40 UTC, miherlosev approved these changes

2021-04-09 06:08 UTC, Farfurix approved these changes

2021-04-09 06:16 UTC, merged