fix: ready to init event in iframe with srcdoc
DevExpress/testcafe-hammerhead pull request #2618
Opened 2021-04-15 07:21 UTC by wentwrong

## Purpose
The ready to init event raised too early in the iframes with the srcdoc attribute. Because of that, TestCafe scripts can't properly initiate themselves. ([init](https://github.com/DevExpress/testcafe/blob/faec4a93682d51a6f51909514b437236899b08c1/src/client/core/page-unload-barrier.js#L82) method of the pageUnloadBarrier gets the 'unload' event of the 'about:blank' iframe and because of that can't properly work further).

## Approach
Don't raise the ready to init event after processing an iframe. Instead, this event will be raised later by self removing script of the iframe with the srcdoc attribute.

## References
functional test in testcafe - https://github.com/DevExpress/testcafe/pull/6142

## Pre-Merge TODO
- [x] Write tests for your proposed changes
- [ ] Make sure that existing tests do not fail

2021-04-15 07:26 UTC, miherlosev requested changes

2021-04-15 07:26 UTC, miherlosev commented on test/client/fixtures/sandbox/iframe-test.js
> +        var $iframe = $('<iframe srcdoc="<h1>simple markup</h1>">').appendTo('body');
Don't use JQuery in client tests

2021-04-20 07:51 UTC, wentwrong commented
Related functional test in TestCafe - https://github.com/DevExpress/testcafe/pull/6142#issuecomment-821275225
All tests are green (except `test-functional-local-headless-chrome`, but this task is green in another run - https://travis-ci.com/github/testcafe-build-bot/testcafe/jobs/499428336)

2021-04-20 08:47 UTC, miherlosev approved these changes

2021-04-20 08:48 UTC, merged