Remove injected head scripts
DevExpress/testcafe-hammerhead pull request #2623
Opened 2021-04-26 06:08 UTC by Farfurix

## Todo
- [ ] check these changes in TestCafe tests

## Purpose
_Describe the problem you want to address or the feature you want to implement._

## Approach
Remove injected `script-hammerhead-shadow-ui` head scripts from DOM

## Pre-Merge TODO
- [x] Write tests for your proposed changes
- [ ] Make sure that existing tests do not fail

2021-04-26 06:31 UTC, Farfurix commented
[testcafe-hammerhead-24.1.1.zip](https://github.com/DevExpress/testcafe-hammerhead/files/6374754/testcafe-hammerhead-24.1.1.zip)

2021-04-27 06:05 UTC, LavrovArtem requested changes

2021-04-27 06:05 UTC, LavrovArtem commented on src/client/index.js.wrapper.mustache
> +window['%hammerhead%'].utils.removeInjectedHeadScript();
I think that the `head` word is extra. Just use the `removeInjectedScript` function name.

2021-04-27 14:35 UTC, LavrovArtem approved these changes

2021-04-29 06:51 UTC, miherlosev requested changes

2021-04-29 06:51 UTC, miherlosev commented on test/server/proxy/request-hooks-test.js
> +    it('TODO: naming', () => {
```js
it('should proxy images if there are registered request filter rules', () {
   const url = 'http://127.0.0.1:2000/page-with-img'
   const rule = new RequestFilterRule(url);

  session.addRequestEventListeners(rule, {
       onRequest: noop
  });

   const options = {
            url:     proxy.openSession(url, session),
            headers: {
                accept: PAGE_ACCEPT_HEADER
            }
        };

   ...
});
```

2021-04-30 07:01 UTC, Farfurix commented
[testcafe-hammerhead-24.1.1.zip](https://github.com/DevExpress/testcafe-hammerhead/files/6403448/testcafe-hammerhead-24.1.1.zip)

2021-05-04 06:05 UTC, Farfurix commented
[testcafe-hammerhead-24.2.0.zip](https://github.com/DevExpress/testcafe-hammerhead/files/6419213/testcafe-hammerhead-24.2.0.zip)

2021-05-05 08:04 UTC, LavrovArtem approved these changes

2021-05-05 08:06 UTC, Farfurix commented
Functional tests are green: https://github.com/DevExpress/testcafe/pull/6175

2021-05-05 08:06 UTC, merged

2021-05-05 08:07 UTC, miherlosev approved these changes