fix for-of destructuring duplicate declarator issue with Object.ArrayPattern
DevExpress/testcafe-hammerhead pull request #2632
Opened 2021-05-13 13:09 UTC by AlexKamaev

2021-05-15 12:38 UTC, LavrovArtem requested changes

2021-05-15 12:38 UTC, LavrovArtem commented on src/processing/script/transformers/for-of.ts
> +function walkDeclarators (node: BlockStatement, action: Function): void {
```suggestion
function walkDeclarators (node: BlockStatement, action: (identifier: Identifier) => void): void {
```

2021-05-15 12:38 UTC, LavrovArtem commented on src/processing/script/transformers/for-of.ts
> +    const isArrayPatternDeclaration = forOfLeft.declarations.length && forOfLeft.declarations[0].id.type === Syntax.ArrayPattern;
```suggestion
    const isArrayPatternDeclaration = forOfLeft.declarations[0]?.id.type === Syntax.ArrayPattern;
```

2021-05-15 12:38 UTC, LavrovArtem commented on src/processing/script/transformers/for-of.ts
> +    const leftIdentifiers = leftDeclaration.elements as Array<Identifier>;
```suggestion
    const leftIdentifiers = leftDeclaration.elements as Identifier[];
```

2021-05-17 06:21 UTC, LavrovArtem approved these changes

2021-05-17 08:03 UTC, miherlosev approved these changes

2021-05-17 08:03 UTC, merged