fixes #2642: instrument sendBeacon via Navigator.prototype
DevExpress/testcafe-hammerhead pull request #2643
Opened 2021-06-01 22:03 UTC by michaelficarra

## Purpose
Fixes #2642. Disallow subversion of instrumentation via `Navigator.prototype.sendBeacon.call`.

## Approach
Instrument `sendBeacon` via `Navigator.prototype` instead of the `navigator` singleton instance. I've noticed that there's other instrumentation with similar failures, but I kept this PR minimal, just addressing #2642.

## References
#2642

## Pre-Merge TODO
- [X] Write tests for your proposed changes
- [X] Make sure that existing tests do not fail

2021-06-03 08:05 UTC, miherlosev commented
Hi @michaelficarra

Thank you for this good work. The tests are red because there are some problems with the `QUnit` test running in `Saucelabs` cloud browsers. We will inform you as soon as this is fixed.

2021-06-03 08:44 UTC, Farfurix requested changes
Hello,

The added test failed here: https://app.saucelabs.com/tests/589a13f0b5d448a686fba69c08d224cb#15

Based on your approach, I believe you need to fix the stored native method in src/client/sandbox/native-methods.ts:
```diff
- this.sendBeacon              = win.navigator.sendBeacon;
+ this.sendBeacon              = win.Navigator.prototype.sendBeacon;
```

2021-06-03 14:26 UTC, michaelficarra commented
@Farfurix Thanks for the feedback. I think I just messed up one of the tests, actually. See the latest commit.

2021-06-04 07:54 UTC, Farfurix commented
@michaelficarra 

You still need to fix the src/client/sandbox/native-methods.ts file. I mentioned it in [my review comment](https://github.com/DevExpress/testcafe-hammerhead/pull/2643#pullrequestreview-675030986).

2021-06-04 14:47 UTC, michaelficarra commented
@Farfurix I didn't make that change because I don't believe that change is necessary. The tests passed in CI on all browsers except Microsoft Edge, which timed out. Are the tests flaky? Can they be re-run?

2021-06-09 01:53 UTC, bakkot commented
@Farfurix `win.navigator.sendBeacon` and `win.Navigator.prototype.sendBeacon` are the same value; it should be fine to refer to it by either name.

2021-06-09 08:53 UTC, Farfurix commented
@michaelficarra @bakkot 

Hello,

I agree that the result will be correct for both `sendBeacon` wrappers on the client page (`window.Navigator.prototype.sendBeacon = wrapper` or `window.navigator.sendBeacon = wrapper`) because they are equal:
```js
window.Navigator.prototype.sendBeacon === window.navigator.sendBeacon
```
I just want to point out that for consistency we should use the saved interface (`Navigator`) method to override it (`window.Navigator.prototype.sendBeacon`).

2021-06-09 15:20 UTC, michaelficarra commented
@Farfurix Okay, done.

2021-06-11 08:26 UTC, Farfurix requested changes
There are some differences related to Navigator in Workers. That's why client tests failed.
We need to rewrite conditions in the following way: in `native-methods.ts`, we should check if `win.Navigator` exists, in other places we should only check our `nativeMethods.sendBeacon` saved method. Also, please rebase your branch to fix Microsoft Edge tests.

2021-06-11 16:07 UTC, michaelficarra commented
@Farfurix Done.

2021-06-15 07:52 UTC, Farfurix requested changes
One more thing to fix in tests (test/client/fixtures/sandbox/node/window-test.js):
```diff
-     if (window.navigator.sendBeacon)
+     if (nativeMethods.sendBeacon)
-         window.checkStringRepresentation(window.navigator.sendBeacon, nativeMethods.sendBeacon);
+         window.checkStringRepresentation(window.Navigator.prototype.sendBeacon, nativeMethods.sendBeacon, 'Navigator.prototype.sendBeacon');
```

2021-06-15 15:40 UTC, michaelficarra commented
@Farfurix Not sure why, but done.

2021-06-16 07:42 UTC, Farfurix commented
@michaelficarra 

These changes are needed due to your approach: we need to check the overridden prototype method in the "wrappers of native functions should return the correct string representations" test. Now, everything looks good to me, and I requested a second review to merge your PR. Thank you for your contribution!

2021-06-16 07:44 UTC, Farfurix approved these changes

2021-06-16 08:05 UTC, merged