feat: added synchronization the tough-cookie with the client
DevExpress/testcafe-hammerhead pull request #2741
Opened 2022-02-14 08:50 UTC by Aleksey28

## Purpose
Add synchronization the tough-cookie with the client after changing them with methods `setCookies` and `deleteCookie`

## Approach
1. Add `syncCookies` property to the Cookies
2. Add filling `syncCookies` in the methods `setCookies` and `deleteCookie`
3. Set new cookies on the service message
4. Add unit tests

## Pre-Merge TODO
- [ ] Write tests for your proposed changes
- [ ] Make sure that existing tests do not fail

2022-02-15 14:38 UTC, LavrovArtem requested changes

2022-02-15 14:38 UTC, LavrovArtem commented on src/session/index.ts
> +        while (true) {
Infinite loop is wrong solution.

Just use `this.cookies.syncCookies.map()` to generate sync cookies.

2022-02-16 09:11 UTC, LavrovArtem requested changes

2022-02-16 09:11 UTC, LavrovArtem commented on src/session/cookies.ts
> +        this.syncCookies           = [];
I think we need to rename this property to `pendingSyncCookies` and make it private.
Also, we need takePendingSyncCookies method, something like this:
```js
takePendingSyncCookies () {
    const cookies = this.pendingSyncCookies;
    
    this.pendingSyncCookies = [];

    return cookies;
}
```

2022-02-16 09:11 UTC, LavrovArtem commented on src/session/cookies.ts
>          const currentUrls = domain && path ? castArray({ domain, path }) : urls;
castArray is unnecessary
just use `[{ domain, path }]`

2022-02-16 13:05 UTC, miherlosev approved these changes

2022-02-16 14:15 UTC, LavrovArtem approved these changes

2022-02-17 07:06 UTC, merged