fix: ExternalCookies type definitions
DevExpress/testcafe-hammerhead pull request #2854
Opened 2023-02-08 12:40 UTC by Artem-Babich

## Purpose
ExternalCookies object is used for filtering cookies. However, its real structure is different form the structure in type definintions

## Approach
Fix definitions

## Pre-Merge TODO
- [ ] Make sure that existing tests do not fail

2023-02-08 12:45 UTC, AlexKamaev approved these changes

2023-02-09 07:04 UTC, Aleksey28 requested changes

2023-02-09 07:04 UTC, Aleksey28 commented on test/functional/run-testcafe-functional-tests.sh
> +git clone --branch Babich-fix-request https://github.com/Artem-Babich/testcafe.git .
Rollback this change

2023-02-10 05:40 UTC, Aleksey28 approved these changes

2023-02-15 10:16 UTC, AlexKamaev approved these changes

2023-02-15 13:06 UTC, merged