proxyless: move the target option from constructor
DevExpress/testcafe-hammerhead pull request #2860
Opened 2023-03-03 06:12 UTC by miherlosev

2023-03-22 09:57 UTC, Aleksey28 requested changes

2023-03-22 09:57 UTC, Aleksey28 commented on src/proxy/index.ts
> +            runRequestPipeline(req, res, serverInfo, this.openSessions, !!(this._proxyOptions as ProxyOptions).proxyless);
Just use here method inProxyless

2023-03-22 09:57 UTC, Aleksey28 commented on src/proxy/index.ts
> +    public get inProxyless (): boolean {
Maybe rename it to `isProxyless`?

2023-03-23 02:58 UTC, miherlosev commented on src/proxy/index.ts
> +        (this._proxyOptions as ProxyOptions).proxyless = true;
Yes. `ProxyOptions` set only in the `proxy.start` method. We cann't set all default values for `ProxylessOptions` in constructor.
```js
constructor () {
   this.proxyOptions = {
      hostname: 'localhost',
      port1:        await getFreePort() -> cannot use async function in constructor.
  };
}
```

2023-03-23 08:49 UTC, merged