fix: add id to websocket transport messages, remove injectables for NA
DevExpress/testcafe-hammerhead pull request #2946
Opened 2023-08-08 10:14 UTC by Artem-Babich

## Purpose
Support NA in TestCafe Studio

## Approach
Do not fill injactables for NA mode. We inject all scripts in the NA Resource Injector. 
By removing these injectables we can not inject our custom scripts in NA mode on TestRun level

## References
_Provide a link to the existing issue(s), if any._

## Pre-Merge TODO
- [ ] Write tests for your proposed changes
- [ ] Make sure that existing tests do not fail

2023-08-08 11:58 UTC, Aleksey28 requested changes
Please, look at my comments.

2023-08-08 11:58 UTC, Aleksey28 commented on src/client/transport/transport-in-socket.ts
> +                if (data.id === id) {
Decrement `this.activeServiceMsgCount` also should be under condition. And in that way will be better to use opposite condition block and just use `return` in it.

2023-08-14 07:14 UTC, miherlosev approved these changes

2023-08-14 11:14 UTC, Aleksey28 approved these changes

2023-08-14 11:15 UTC, merged