fix: support non-canonicalised srcset attribute name #2958
DevExpress/testcafe-hammerhead pull request #2968
Opened 2023-10-18 08:47 UTC by gg-kialo

Some frameworks, like React, use non-canonicalised attribute names. The spec and browsers allow this, but hammerhead is only checking if the attribute name without canonicalisation matches `srcset`.

By using the `loweredAttr` for the comparison, hammerhead will be more accepting of inputs and resolve srcset issues with React projects (fixes #2958).

See https://github.com/facebook/react/issues/10863 for more background.

## Purpose

Fixes #2958 to better support `srcSet` attributes in React applications.

## Approach

Canonicalises the attribute name before comparing to `srcset`.

## References
Related react issue (and there are various duplicates of this) - https://github.com/facebook/react/issues/10863

## Pre-Merge TODO
- [x] Write tests for your proposed changes
- [ ] Make sure that existing tests do not fail (unable to get the tests to run)

2023-10-18 08:50 UTC, gg-kialo commented
fyi: both locally and in github codespaces I've been unable to get the tests to run. After running `gulp test-client` nothing happens after QUnit server starts to listen.

```
...
[10:41:29] Finished 'lint' after 12 s
[10:41:29] Finished 'build' after 17 s
[10:41:29] Starting 'test-client-run'...
QUnit server listens on http://localhost:2000
```

2023-10-18 14:07 UTC, Aleksey28 requested changes
Hi @gg-kialo,

Thank you for your contribution. We really appreciate your help. To preserve this fix from future changes, please add a test that checks this behavior.

2023-10-18 15:13 UTC, gg-kialo commented
I've pushed with an added test. I managed to figure how to get them to run locally (you have to open the qunit server :facepalm:).

fyi, I'll be OoO until Tuesday.

2023-10-20 11:02 UTC, Aleksey28 requested changes
Thank you for your contribution. Please take a look at my suggestions.

2023-10-24 11:03 UTC, Aleksey28 approved these changes

2023-10-24 12:24 UTC, merged