fixed: Sockets hanging
DevExpress/testcafe-hammerhead pull request #2976
Opened 2023-11-13 08:02 UTC by PavelMor25

## Purpose
Due to changes in Node.js, the old approach of destroying the request is no longer suitable, as the check within the method itself determines that it has already been destroyed.

## Approach
We have added a method in RequestPipelineContext that bypasses this check.

## References
[issue 7097](https://github.com/DevExpress/testcafe/issues/7097)

## Pre-Merge TODO
- [ ] Write tests for your proposed changes
- [ ] Make sure that existing tests do not fail

2023-11-14 06:00 UTC, AlexKamaev approved these changes

2023-11-14 08:26 UTC, aleks-pro commented on src/request-pipeline/context/index.ts
> +        if (this.req.socket)
We discussed in private and decided to add `req.destroy()` calling in case of some changes in future node js version

2023-11-14 11:23 UTC, aleks-pro requested changes

2023-11-14 11:23 UTC, aleks-pro commented on src/request-pipeline/context/index.ts
> +            this.req.socket.destroy();
What if `this.req.socket` expression returns `null` or `undefined`? It looks like we will get null ref exception

2023-11-14 11:23 UTC, aleks-pro commented on src/request-pipeline/context/index.ts
> +        // For Node versions greater than 15.4, we check the socket. If req.destroy didn't destroy it, we call the corresponding method of the socket.
```suggestion
        // NOTE: For Node versions greater than 15.4, we check the socket. If req.destroy didn't destroy it, we call the corresponding method of the socket.
```

2023-11-15 05:53 UTC, aleks-pro approved these changes

2023-11-16 07:19 UTC, merged