fix: Handling of native dialogs inconsistent with handling in Firefox (closes #6815)
DevExpress/testcafe-hammerhead pull request #2980
Opened 2023-11-21 15:52 UTC by PavelMor25

When adding the `onbeforeunload` event to a page, inside of which there is `e.preventDefault()` and `e.returnResult` with an empty string, Hammerhead overrides the prevented property, causing the native dialog not to be recorded in the TestCafe session storage.

2023-11-23 08:47 UTC, AlexKamaev requested changes

2023-11-23 08:47 UTC, AlexKamaev commented on test/client/fixtures/sandbox/event/unload-test.js
> +                        reload: true,
is `reload` always `true`? do we really need id?

2023-11-23 08:47 UTC, AlexKamaev commented on test/client/data/unload/iframe-beforeunload.html
> +    var reload = document.querySelector('#reload');
do we need this line?

2023-11-23 08:47 UTC, AlexKamaev commented on test/client/data/unload/iframe-beforeunload.html
> +            }
```JS
hhPostMessage(window.parent, [e.prevented, '*'])
```

2023-11-23 08:47 UTC, AlexKamaev commented on test/client/data/unload/iframe-beforeunload.html
> +        if (!reload)
do we need this `reload`?

2023-11-23 08:47 UTC, AlexKamaev commented on test/client/data/unload/iframe-beforeunload.html
> +            if (prevented)
maybe not `prevented` but `needPrevent`?

2023-11-23 09:38 UTC, AlexKamaev approved these changes

2023-11-23 09:45 UTC, Aleksey28 commented on test/client/fixtures/sandbox/event/unload-test.js
> +            title:         'and prevented native dialog with empty returnValue and e.preventDefault',
```suggestion
            title:         'to prevent opening native dialog with empty return Value and e.preventDefault',
```

2023-11-23 09:47 UTC, Aleksey28 commented on test/client/fixtures/sandbox/event/unload-test.js
> +            title:         'without prevented native dialog',
```suggestion
            title:         'without preventing the opening native dialog',
```

2023-11-23 09:49 UTC, Aleksey28 commented on test/client/fixtures/sandbox/event/unload-test.js
> +            title:         'and prevented native dialog with returnValue',
```suggestion
            title:         'the handler must be called to prevent opening native dialog with returnValue',
```

2023-11-23 09:51 UTC, Aleksey28 commented on test/client/fixtures/sandbox/event/unload-test.js
> +                    expectPrevent ? ok(isPrevented) : notOk(isPrevented);
```suggestion
                    expect(isPrevented).eql(expectPrevent);
```

2023-11-24 07:39 UTC, Aleksey28 approved these changes

2023-11-24 07:50 UTC, AlexKamaev approved these changes

2023-11-24 07:50 UTC, merged