testing
DevExpress/testcafe-hammerhead pull request #3004
Opened 2024-05-07 15:42 UTC by Bayheck

## Purpose
_Describe the problem you want to address or the feature you want to implement._

## Approach
_Describe how your changes address the issue or implement the desired functionality in as much detail as possible._

## References
_Provide a link to the existing issue(s), if any._

## Pre-Merge TODO
- [ ] Write tests for your proposed changes
- [ ] Make sure that existing tests do not fail

2024-05-22 07:33 UTC, Aleksey28 approved these changes

2024-05-22 08:02 UTC, PavelMor25 approved these changes

2024-05-29 06:15 UTC, Aleksey28 requested changes
Great, look at my comment please

2024-05-29 06:15 UTC, Aleksey28 commented on test/client/fixtures/sandbox/node/classes-test.js
> +    if (isChrome && !isMobile) {
I think we can run these tests also under other browsers

2024-05-29 09:37 UTC, Aleksey28 approved these changes

2024-05-29 10:05 UTC, merged