Remove request
DevExpress/testcafe-hammerhead pull request #3010
Opened 2024-06-27 05:06 UTC by PavelMor25

## Purpose
_Describe the problem you want to address or the feature you want to implement._

## Approach
_Describe how your changes address the issue or implement the desired functionality in as much detail as possible._

## References
_Provide a link to the existing issue(s), if any._

## Pre-Merge TODO
- [ ] Write tests for your proposed changes
- [ ] Make sure that existing tests do not fail

2024-07-02 11:11 UTC, Bayheck approved these changes

2024-07-09 07:23 UTC, Aleksey28 requested changes

2024-07-09 07:23 UTC, Aleksey28 commented on test/server/common/utils.js
> +    const url = typeof options === 'string'
Create one variable, for example `isString` or `isUrl`, and reuse it

2024-07-11 06:52 UTC, Aleksey28 approved these changes

2024-07-11 10:24 UTC, merged